[platformio]
default_envs = t_internet_com
src_dir = firmware/arduino/ticom_board_check

[env:t_internet_com]
platform = espressif32
board = esp-wrover-kit
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit NeoPixel
build_flags =
    -DCORE_DEBUG_LEVEL=3
